version: "3.8"
services:
  # https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
  grafana:
    image: docker.io/grafana/grafana-oss:10.0.8
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - ./_grafana_data:/var/lib/grafana:Z

  prometheus:
    # https://hub.docker.com/r/prom/prometheus
    # https://prometheus.io/docs/introduction/first_steps/
    image: docker.io/prom/prometheus:v2.47.1
    container_name: prometheus
    restart: unless-stopped
    ports:
     - '9090:9090'
    volumes:
      - ./conf/_prometheus:/etc/prometheus:Z

  alertmanager:
    # https://hub.docker.com/r/prom/alertmanager
    # https://www.theairtips.com/post/setting-up-alertmanager-with-docker-compose
    image: docker.io/prom/alertmanager:v0.26.0
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./conf/_alertmanager:/config:Z
      - ./_alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug
