quarkus:
  http:
    enable-compression: true
    test-port: 8082
  container-image:
    image: local/alertmanager-evateam
  native:
    resources:
      includes: '*.json'

  log:
    category:
      "info.hubbitus":
        level: DEBUG
      # By https://stackoverflow.com/a/68220910/307525
      # Produce a lot of info about HTTP traffic for the debug
#      "org.apache.http":
#        level: DEBUG
    console:
      format: '%d{yyyy-MM-dd HH:mm:ss.SX} %-5p [%l] (%t) %s%e%n'

    sentry:
      # Disabled until DSN will be created
      enabled: false
      debug: false
      level: WARN
      traces-sample-rate: 1
      in-app-packages: info.hubbitus
      # dsn:

# Disable sentry for the test execution
"%test":
  quarkus:
    log:
      sentry:
        # Default disabled, must be enabled per configuration
        enabled: false

eva:
  api:
    base: https://eva-lab.gid.team/
  # Must be provided securely, e.g. by env variable EVA_API_TOKEN
#  token:

