quarkus:
  http:
    enable-compression: true
    test-port: 8082
  container-image:
    image: local/alertmanager-evateam
  native:
    resources:
      includes: '*.json'
#    builder-image: ghcr.io/graalvm/native-image-community:24.0.2
#    builder-image: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-24
    builder-image: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-26.0.0_0

  log:
    level: WARN
    category:
      "io.quarkus":
        level: WARN
      "info.hubbitus":
        level: DEBUG
      "info.hubbitus.alertmanager":
        level: DEBUG
      # By https://stackoverflow.com/a/68220910/307525
      # Produce a lot of info about HTTP traffic for the debug
#      "org.apache.http":
#        level: DEBUG
    console:
      format: '%d{yyyy-MM-dd HH:mm:ss.SX} %-5p [%l] (%t) %s%e%n'

    sentry:
      # Disabled until DSN will be created
      enabled: false
      debug: false
      level: WARN
      traces-sample-rate: 1
      in-app-packages: info.hubbitus
      # dsn:

# Disable sentry for the test execution
"%test":
  quarkus:
    log:
      sentry:
        # Default disabled, must be enabled per configuration
        enabled: false

app:
  # Special value "auto" means to use Host HTTP header automatically.
  # Value without trailing /
  baseURL: auto
#  baseURL: https://eva-alert.k8s-dev.gid.team
eva:
  api:
    base: https://eva-lab.gid.team/
  # Must be provided securely, e.g. by env variable EVA_API_TOKEN
#  token:

