global:
  scrape_interval:     15s
  evaluation_interval: 15s

  #  alerting:
  #    alert_relabel_configs:

  external_labels:
    global_label_1: 1

rule_files:
  - 'alerts/bi.yml'
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alert_relabel_configs:
    - target_label: eva__project
      replacement: data-alerts
    - target_label: eva__issue_type_name
      replacement: Task
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

